In [1]:
import pandas as pd

# Read Data

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data.head() #top five values

fiver  age  headach  runnyNose  persistent Cough  sore throatr  \
0  101.074377   11        0          0                 1             0   
1  101.633515   96        1          0                 0             0   
2  100.537922   21        0          1                 0             1   
3   99.744629   94        1          1                 0             0   
4   98.792928   22        0          0                 1             0   

   diffBreath  loss of smell  innfectionProb  
0           0              0               0  
1           1              0               0  
2           1              0               0  
3           1              1               1  
4          -1              1               0

In [4]:
data.tail()

fiver  age  headach  runnyNose  persistent Cough  sore throatr  \
1080   98.374678   15        1          0                 0             0   
1081  101.322187   89        0          0                 1             0   
1082   99.513842   62        0          0                 0             1   
1083   99.074097   31        1          1                 1             1   
1084   99.074252   88        1          1                 1             0   

      diffBreath  loss of smell  innfectionProb  
1080           1              0               1  
1081           0              1               0  
1082          -1              0               0  
1083           0              0               1  
1084           1              0               0

In [5]:
data.info() #give info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   fiver             1085 non-null   float64
 1   age               1085 non-null   int64  
 2   headach           1085 non-null   int64  
 3   runnyNose         1085 non-null   int64  
 4   persistent Cough  1085 non-null   int64  
 5   sore throatr      1085 non-null   int64  
 6   diffBreath        1085 non-null   int64  
 7   loss of smell     1085 non-null   int64  
 8   innfectionProb    1085 non-null   int64  
dtypes: float64(1), int64(8)
memory usage: 76.4 KB


In [6]:
data.describe()

fiver          age      headach    runnyNose  persistent Cough  \
count  1085.000000  1085.000000  1085.000000  1085.000000       1085.000000   
mean    100.019557    51.540092     0.517051     0.513364          0.504147   
std       1.159119    28.694753     0.499940     0.500052          0.500213   
min      98.008788     1.000000     0.000000     0.000000          0.000000   
25%      99.037105    27.000000     0.000000     0.000000          0.000000   
50%     100.055143    51.000000     1.000000     1.000000          1.000000   
75%     101.006501    76.000000     1.000000     1.000000          1.000000   
max     101.999064   100.000000     1.000000     1.000000          1.000000   

       sore throatr   diffBreath  loss of smell  innfectionProb  
count   1085.000000  1085.000000    1085.000000     1085.000000  
mean       0.491244     0.009217       0.507834        0.529032  
std        0.500154     0.811533       0.500169        0.499387  
min        0.000000    -1.000000       0.000000        0.000000  
25%        0.000000    -1.000000       0.000000        0.000000  
50%        0.000000     0.000000       1.000000        1.000000  
75%        1.000000     1.000000       1.000000        1.000000  
max        1.000000     1.000000       1.000000        1.000000

In [7]:
# Checking existence of null value in the dataset

data.isnull().sum()

# No null value is present in the dataset

fiver               0
age                 0
headach             0
runnyNose           0
persistent Cough    0
sore throatr        0
diffBreath          0
loss of smell       0
innfectionProb      0
dtype: int64

In [8]:
data['diffBreath'].value_counts()

 0    371
 1    362
-1    352
Name: diffBreath, dtype: int64

# Train test Split

In [9]:
import numpy as np #train test split technique for evaluating the performance of a machine learning algorithm.
#The training dataset is used to prepare a model, to train it
#The “training” data set is the general term for the samples used to create the model, while the “test” or “validation” data set is used to qualify performance.
#A test set is therefore a set of examples used only to assess the performance

In [10]:
def split(data,ratio):
    np.random.seed(42) #freeze random value
    shuffled = np.random.permutation(len(data)) #random shuffle num generate krbe
    test_set_size = int(len(data)*ratio)
    test_indicies = shuffled[:test_set_size] #create value according to testsize row and colum
    train_indicies = shuffled[test_set_size:]  
    return data.iloc[train_indicies], data.iloc[test_indicies]

In [11]:
np.random.permutation(7) #permutaion ki kre

array([1, 3, 2, 6, 5, 4, 0])

In [12]:
train , test = split(data,0.2)

In [31]:
len(train)

868

In [32]:
len(test)

217

In [15]:
X_train = train[['fiver','age','headach','runnyNose','persistent Cough','sore throatr','diffBreath','loss of smell']].to_numpy()
X_test = test[['fiver','age','headach','runnyNose','persistent Cough','sore throatr','diffBreath','loss of smell']].to_numpy()

In [16]:
X_train #numpy array pabo

array([[ 99.42565649,  34.        ,   1.        , ...,   1.        ,
          0.        ,   1.        ],
       [101.2857481 ,  19.        ,   1.        , ...,   1.        ,
          0.        ,   0.        ],
       [ 99.17931496,  77.        ,   1.        , ...,   0.        ,
          0.        ,   1.        ],
       ...,
       [101.7582479 ,  49.        ,   0.        , ...,   1.        ,
         -1.        ,   0.        ],
       [101.9558805 ,  31.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [101.9621554 ,  66.        ,   1.        , ...,   0.        ,
          1.        ,   1.        ]])

In [17]:
X_test

array([[ 99.18958532,  40.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [ 99.90429307,   8.        ,   0.        , ...,   1.        ,
         -1.        ,   1.        ],
       [100.8431006 ,  79.        ,   1.        , ...,   1.        ,
         -1.        ,   1.        ],
       ...,
       [100.9488025 ,  58.        ,   0.        , ...,   1.        ,
          0.        ,   1.        ],
       [ 98.73389005,  57.        ,   1.        , ...,   1.        ,
         -1.        ,   1.        ],
       [101.6436807 ,  68.        ,   1.        , ...,   0.        ,
         -1.        ,   1.        ]])

In [18]:
Y_train = train[['innfectionProb']].to_numpy().reshape(868,)
Y_test = test[['innfectionProb']].to_numpy().reshape(217,)

In [19]:
Y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression()

dfmodel =clf.fit(X_train,Y_train) #best form e rakhte hobe
dfmodel

LogisticRegression()

In [22]:
input_user = [99.179315,77, 1, 0, 0, 0, 0, 1]
inf_prob = clf.predict_proba([input_user])[0][1]

In [23]:
inf_prob

0.5145293774767351

In [33]:
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [34]:
# print metric to get performance
print("Accuracy: ",clf.score(X_test, Y_test) * 100)

Accuracy:  56.68202764976959


In [26]:
pred = clf.predict([input_user])

In [27]:
pred

array([1], dtype=int64)

In [28]:
if pred == 1:
    print("paitent is affected")
else:
    print("paitent is not affected")

paitent is affected


In [29]:
import pickle

In [30]:
file = open('Corona_vir_project.pkl','wb')
pickle.dump(dfmodel,file)